version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
  deploy:
    machine:
      enabled: true
    steps:
      - run: 
          name: Deploy Over SSH
          command: |
            scp -P 7822 -r build/* ttuz@nl1-ls2.a2hosting.com:/tt.uz/
workflows:
   build-and-deploy:
     jobs:
       - build-and-test
       - deploy:
           requires:
             - build-and-test # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch



               