version: 2.1
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ff:50:93:9a:50:4f:5d:ee:0f:77:d4:99:ac:01:06:4d"
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: show folders
          command: ls
      - run:
          name: show folders
          command: pwd
      - run: 
          name: Deploy Over SSH
          command: |
            ssh -i id_rsa -p 7822 ttuz@nl1-ls2.a2hosting.com 'cd public_html/tt.uz/ && git pull'
  deploy:
    machine:
      enabled: true
    steps:
      - run: 
          name: Show folders
          command: |
            ls
      - run: 
          name: Show directory
          command: |
            pwd
      - run: 
          name: Deploy Over SSH
          command: |
            scp -P 7822 -r ./build ttuz@nl1-ls2.a2hosting.com:/tt.uz/
workflows:
   build-and-deploy:
     jobs:
       - build-and-test
       - deploy:
           requires:
             - build-and-test # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch



               